# Generated by Django 3.2.5 on 2021-08-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsstory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='img_url',
            field=models.TextField(default='https://placedog.net/200/300'),
        ),
    ]
